In [21]:
import numpy as np

In [22]:
arr = np.arange(0, 11)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr[8]

np.int64(8)

In [25]:
arr[1:5]

array([1, 2, 3, 4])

In [26]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [27]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [28]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [29]:
arr[0:5] = 100

In [30]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [31]:
arr = np.arange(0, 11)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
slice_of_arr = arr[0:6]

In [34]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [37]:
slice_of_arr[:] = 99

In [38]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [39]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [40]:
arr_copy = arr.copy()

In [41]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [44]:
arr_copy[:] = 100

In [45]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [46]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [47]:
arr_2d = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])

In [48]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [58]:
arr_2d[1,2]

np.int64(30)

In [59]:
arr_2d[1][2]

np.int64(30)

In [60]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [61]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [63]:
arr = np.arange(1, 11)

In [64]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
bool_arr = arr > 5

In [68]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [69]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [70]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [71]:
arr[arr < 3]

array([1, 2])

In [72]:
arr_2d = np.arange(50).reshape((5, 10))

In [76]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [74]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])